### ISSUE TITLE
What dataset is CBOE_VX from?

### ISSUE THREAD

**Issue by MichaelWS** [dougransom/vix_utils#3]
Doug awesome work here.  what dataset is CBOE VX data from ?

**Comment by dougransom** [comment]
Back at that time it was quandle, but now I am working on downloading it from cboe.

**Comment by dougransom** [comment]
It is downloading from CBOE now back to the beginning of time.
https://www.cboe.com/us/futures/market_statistics/historical_data/

Work in progress but you can download it from remove_quandl branch at tag March_2023_downloads_work,
`pip install -e .[dev,examples]`
in the examples folder run
`py c_plot_vix_term_structure.py`

if it goes ok you can see the term structure history.

**Comment by MichaelWS** [comment]
Great

**Comment by dougransom** [comment]
as of today it is working.  install from pip or github as you need.
