### ISSUE TITLE
missing futures data front 2nd month, and before same futures when it's was 3rd month... data is NaN?

### ISSUE THREAD

**Issue by githubbla** [dougransom/vix_utils#31]
![Screenshot 2024-04-24 at 13 48 02](https://github.com/dougransom/vix_utils/assets/12095960/3076686c-a4a9-470a-931e-b969956e4752)

**Comment by githubbla** [comment]
@dougransom  could you please look into issue?

**Comment by githubbla** [comment]
https://en.wikipedia.org/wiki/Juneteenth
19-Jun
US public holiday from 2021!!
🤯

**Comment by dougransom** [comment]
> @dougransom, @gnzsnz
> 
> https://en.wikipedia.org/wiki/Juneteenth 19-Jun US public holiday from 2021!! 🤯

https://github.com/rsheftel/pandas_market_calendars/issues/261

**Comment by dougransom** [comment]
@gnzsnz Thanks for fixing it, I have merged it in, along with a unit test and a requirement for latest pandas market calendars.  

Though this error was mine, we get similar errors when the Pandas market calendars miss a holiday.

**Comment by dougransom** [comment]
Fixed in release 0.1.6 on PyPi.
